# Generated by Django 4.2.4 on 2023-08-28 05:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_backet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backet',
            new_name='Basket',
        ),
    ]
